---
- name: Add authorized keys for root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  loop: "{{ ssh_keys_to_add }}"

- name: Remove authorized keys for root
  ansible.posix.authorized_key:
    user: root
    state: absent
    key: "{{ item }}"
  loop: "{{ ssh_keys_to_remove }}"
