---

- name: Get user database
  ansible.builtin.getent:
    database: passwd

- name: Add SSH keys to users
  ansible.builtin.include_tasks: "add_ssh_keys.yml"
  loop: "{{ ssh_keys_users_to_add_to }}"
  loop_control:
    loop_var: user

- name: Remove SSH keys of users
  ansible.builtin.include_tasks: "remove_ssh_keys.yml"
  loop: "{{ ssh_keys_users_to_remove_from }}"
  loop_control:
    loop_var: user
